apiVersion: v1
kind: Service
metadata:
  name: project-service
  labels:
    app: project-service
    project: codesync
spec:
  selector:
    app: project-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: project-service
  labels:
    app: project-service
    project: codesync
spec:
  to:
    kind: Service
    name: project-service
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
