apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  labels:
    app: file-service
    project: codesync
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
        project: codesync
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: file-service
          image: image-registry.openshift-image-registry.svc:5000/mr-aksthegreat030420-dev/file-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
              name: http
              protocol: TCP
          envFrom:
            - secretRef:
                name: file-service-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            initialDelaySeconds: 70
            periodSeconds: 15
            failureThreshold: 3
