apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secrets
type: Opaque
stringData:
  JWT_SECRET: "<set-strong-jwt-secret>"
  EUREKA_DEFAULT_ZONE: "http://<set-eureka-username>:<set-eureka-password>@eureka-service:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  labels:
    app: api-gateway-service
    project: codesync
spec:
  selector:
    app: api-gateway-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: api-gateway-service
  labels:
    app: api-gateway-service
    project: codesync
spec:
  to:
    kind: Service
    name: api-gateway-service
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

