apiVersion: apps/v1
kind: Deployment
metadata:
  name: collab-service
  labels:
    app: collab-service
    project: codesync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collab-service
  template:
    metadata:
      labels:
        app: collab-service
        project: codesync
    spec:
      containers:
        - name: collab-service
          image: image-registry.openshift-image-registry.svc:5000/mr-aksthegreat030420-dev/collab-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
              name: http
          envFrom:
            - secretRef:
                name: collab-service-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8084
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            initialDelaySeconds: 70
            periodSeconds: 15
            failureThreshold: 3
